#pragma once

// Standart
#include <fstream>
#include <iostream>
#include <sstream>
#include <algorithm>
#include <functional>
#include <memory>
#include <thread>
#include <utility>
#include <cstdlib>
#include <cstddef>
#include <filesystem>
#include <cstring>
#include <string>
#include <stack>
#include <deque>
#include <array>
#include <vector>
#include <utility>
#include <set>
#include <map>
#include <bit>
#include <unordered_map>
#include <unordered_set>
#include <optional>

// OPENGL/VULKAN
#include <glad/glad.h>
#include <GLFW/glfw3.h>

// GLM
#include <glm/glm.hpp>
#include <glm/ext.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/compatibility.hpp>
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/norm.hpp>
#include "glm/gtx/hash.hpp"